/**
 * helper: send-transfer
 *
 * Send real SEP-41 (Soroban token) USDC transfers on testnet from the
 * funded SIMULATION_SOURCE_ACCOUNT to a destination (optionally funded via
 * Friendbot). This generates the on-chain activity the indexer ingests.
 *
 * Because SIMULATION_SOURCE_ACCOUNT is (or should be) a monitored account,
 * these transfer events will be attributed as x402 settlements and appear
 * in the dashboard in real time.
 *
 * Usage:
 *   npm -w @spendguard/indexer run send:transfer -- <amount_USDC> [destination]
 *
 * Defaults to 5 USDC when no amount is given, and mints-and-funds a fresh
 * destination from Friendbot when none is provided.
 */

import {
  Keypair,
  Contract,
  Asset,
  Operation,
  TransactionBuilder,
  nativeToScVal,
  rpc,
} from "@stellar/stellar-sdk";
import { loadScriptEnv } from "./env.js";
import { loadAccount } from "./horizon.js";

// ── Testnet USDC ──────────────────────────────────────────────────────
//
// The monitored asset contract (X402_ASSET_CONTRACT_ID, the testnet USDC
// Stellar Asset Contract CBIELTK6Y…) wraps the classic USDC issued by this
// testnet issuer. SEP-41 SAC transfers require the receiving account to
// hold a trustline to the underlying asset, so fresh destinations are
// given a ChangeTrust op before the transfer. Override the issuer via
// X402_ASSET_ISSUER when pointing at a different SAC.
// The public testnet Friendbot. It is a standalone host — it is NOT
// reachable by appending "/friendbot" to the Soroban RPC URL.
const FRIENDBOT_URL = "https://friendbot.stellar.org";

/**
 * The issuer of the monitored asset, read lazily: scripts load
 * X402_ASSET_ISSUER from .env.local inside loadScriptEnv(), which runs
 * AFTER this module is imported, so a module-scope const would always
 * fall back to the Circle testnet USDC issuer.
 */
function usdcIssuer(): string {
  return (
    process.env.X402_ASSET_ISSUER?.trim() ||
    "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
  );
}

const [amountArg, destinationArg] = process.argv.slice(2);

function log(msg: string, meta?: unknown): void {
  const ts = new Date().toISOString();
  const metaStr = meta ? ` ${JSON.stringify(meta)}` : "";
  console.log(`[${ts}] [send-transfer] ${msg}${metaStr}`);
}

async function fundViaFriendbot(address: string): Promise<void> {
  const url = new URL(FRIENDBOT_URL);
  url.searchParams.set("addr", address);
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Friendbot failed: ${res.status} ${await res.text()}`);
  }
  log("Friendbot funded destination", { address });
}

/**
 * Poll for a submitted transaction until it settles (or times out).
 * getTransaction right after sendTransaction usually returns NOT_FOUND
 * because the ledger has not yet included the tx.
 */
async function waitForTransaction(
  server: rpc.Server,
  hash: string,
  timeoutMs = 30_000,
): Promise<rpc.Api.GetTransactionResponse> {
  const deadline = Date.now() + timeoutMs;
  let result = await server.getTransaction(hash);
  while (result.status === "NOT_FOUND" && Date.now() < deadline) {
    await new Promise((resolve) => setTimeout(resolve, 1_500));
    result = await server.getTransaction(hash);
  }
  return result;
}

/**
 * Add a USDC trustline to a fresh destination so it can receive SAC
 * transfers. Requires the destination keypair (only available for the
 * friendbot-funded destination generated by this script).
 */
async function addUsdcTrustline(
  keypair: Keypair,
  networkPassphrase: string,
  rpcUrl: string,
): Promise<void> {
  const server = new rpc.Server(rpcUrl, {
    allowHttp: rpcUrl.startsWith("http://"),
  });
  const usdcAsset = new Asset("USDC", usdcIssuer());
  const account = await loadAccount(keypair.publicKey());

  const tx = new TransactionBuilder(account, {
    fee: "100",
    networkPassphrase,
  })
    .addOperation(Operation.changeTrust({ asset: usdcAsset }))
    .setTimeout(30)
    .build();
  tx.sign(keypair);

  const send = await server.sendTransaction(tx);
  log("Submitted trustline ChangeTrust", {
    status: send.status,
    hash: send.hash,
  });

  if (send.status === "ERROR") {
    throw new Error(`Trustline tx rejected: ${JSON.stringify(send)}`);
  }
  const result = await waitForTransaction(server, send.hash);
  if (result.status !== "SUCCESS") {
    throw new Error(
      `Trustline transaction failed: ${result.status} — ${JSON.stringify(result)}`,
    );
  }
  log("USDC trustline established", { address: keypair.publicKey() });
}

/**
 * Retry a network-heavy step a few times. The public testnet RPC is
 * intermittently flaky ("fetch failed"); a retry usually succeeds.
 * Callers must pass an idempotent-ish closure (fresh sequence per call).
 */
async function withRetry<T>(
  fn: () => Promise<T>,
  attempts = 3,
  delayMs = 2_000,
): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      if (i < attempts - 1) {
        log(`Attempt ${i + 1} failed, retrying`, {
          error: err instanceof Error ? err.message : String(err),
        });
        await new Promise((resolve) => setTimeout(resolve, delayMs));
      }
    }
  }
  throw lastErr;
}

async function main(): Promise<void> {
  const env = loadScriptEnv();

  const amountUsdc = amountArg ? Number.parseFloat(amountArg) : 5;
  if (Number.isNaN(amountUsdc) || amountUsdc <= 0) {
    throw new Error(`Invalid amount: "${amountArg}"`);
  }
  const amountStroops = BigInt(Math.round(amountUsdc * 1e7)); // 7 decimals

  const source = Keypair.fromSecret(env.simulationSourceAccountSecret);
  const from = source.publicKey();

  const server = new rpc.Server(env.sorobanRpcUrl, {
    allowHttp: env.sorobanRpcUrl.startsWith("http://"),
  });

  let to = destinationArg;
  if (!to) {
    const fresh = Keypair.random();
    to = fresh.publicKey();
    await fundViaFriendbot(to);
    // ChangeTrust is idempotent, so retrying is safe.
    await withRetry(() =>
      addUsdcTrustline(fresh, env.networkPassphrase, env.sorobanRpcUrl),
    );
  } else if (!to.startsWith("G")) {
    throw new Error(`Destination must be a G... address, got: "${to}"`);
  }

  log("Sending transfer", {
    asset: env.x402AssetContractId,
    from,
    to,
    amountUsdc,
    amountStroops: amountStroops.toString(),
  });

  // Build → simulate → assemble → submit inside the retry loop so a
  // transient RPC failure doesn't kill the run. A fresh account is loaded
  // per attempt so the sequence number always matches the chain. Only
  // network-level failures are retried; a hard rejection (send.status ===
  // "ERROR") is checked after the loop so it fails fast.
  const contract = new Contract(env.x402AssetContractId);
  const send = await withRetry(async () => {
    const account = await loadAccount(from);
    const tx = new TransactionBuilder(account, {
      fee: "100",
      networkPassphrase: env.networkPassphrase,
    })
      .addOperation(
        contract.call(
          "transfer",
          nativeToScVal(from, { type: "address" }),
          nativeToScVal(to, { type: "address" }),
          nativeToScVal(amountStroops, { type: "i128" }),
        ),
      )
      .setTimeout(30)
      .build();

    // Soroban transactions MUST be simulated first: the response carries
    // the footprint, auth entries and resource fees that
    // assembleTransaction bakes into the final envelope. Submitting a
    // hand-built tx without simulation is rejected with txMalformed.
    const simulated = await server.simulateTransaction(tx);
    if (rpc.Api.isSimulationError(simulated)) {
      throw new Error(`Simulation failed: ${JSON.stringify(simulated)}`);
    }
    const assembled = rpc.assembleTransaction(tx, simulated).build();
    assembled.sign(source);

    const send = await server.sendTransaction(assembled);
    log("Submitted", { status: send.status, hash: send.hash });
    return send;
  });

  if (send.status === "ERROR") {
    throw new Error(`Transaction rejected: ${JSON.stringify(send)}`);
  }

  const result = await waitForTransaction(server, send.hash);
  if (result.status !== "SUCCESS") {
    throw new Error(
      `Transaction failed: ${result.status} — ${JSON.stringify(result)}`,
    );
  }
  log("Transaction succeeded", { hash: send.hash, to });
}

main().catch((err) => {
  console.error(`[send-transfer] Failed:`, err);
  process.exit(1);
});
